# AWS Infra playbook
---

- hosts: Node
  connection: local
  gather_facts: False
  vars_files: 
    - /home/ubuntu/Ansible/Ansible_Assignment03/aws_keys.txt
  vars:
    key_name: /home/ubuntu/Ansible/Ansible_Assignment_3/Vikas.Virginia.pem             # Key used for SSH
    region: us-east-1      # Region may affect response and pricing
    image: ami-04b70fa74e45c3917 # look in ec2 > ami (filter owner alias: amazon) or amis of manually launched instances
    id: "ansible"
    instance_type: t2.micro     # Choose instance type, check AWS for pricing
    # vpc_id: subnet-012345
    sec_group: "ansible-all-traffic"
    ansible_python_interpreter: "/usr/bin/python3"  # Replace with the correct path

  tasks:
    - name: Create security group
      amazon.aws.ec2_security_group:
        name: "{{ sec_group }}"
        description: "Sec group for Ansible EC2 infra"
        region: "{{ region }}"
        aws_access_key: "{{ ec2_access_key }}"  # From vault as defined
        aws_secret_key: "{{ ec2_secret_key }}"  # From vault as defined
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow SSH
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
            rule_desc: allow HTTP
          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: 0.0.0.0/0
            rule_desc: allow HTTP Alt

    - name: Amazon EC2 | Create Key Pair
      amazon.aws.ec2_key:
        name: "{{ key_name }}"
        region: "{{ region }}"
        aws_access_key: "{{ ec2_access_key }}"  # From vault as defined
        aws_secret_key: "{{ ec2_secret_key }}"  # From vault as defined
        key_material: "{{ lookup('file', '/home/opstree/.ssh/my_aws.pub') }}"

    - name: Create an instance with a public IP address
      amazon.aws.ec2_instance:
        name: "ansible-nginx"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        security_group: "{{ sec_group }}"
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        region: "{{ region }}"
        network:
          assign_public_ip: yes
        image_id: "{{ image }}"
      register: ec2_result  

    - name: Debug output for ec2_result.instances[0].public_ip_address
      debug:
        msg: "The instance Public IP is {{ ec2_result.instances[0].public_ip_address }}"

