---
- name: SSH into EC2 instance
  hosts: all
  tasks:
    - name: Wait for SSH to be available
      wait_for:
        host: "{{ ec2_public_ip }}"
        port: 22
        delay: 10
        timeout: 600

    - name: SSH into EC2 instance
      command: ssh ubuntu@{{ ec2_public_ip }}
      
