---
- name: Deployment of Spring3HibernateApp 
  hosts: tomcat
  become: yes
  tasks:

    - name: Install pakages
      apt:
        update_cache: yes
        name: 
          - openjdk-11-jdk
          - maven
          - tomcat10
          - tomcat10-admin
        state: present

    - name: Create directory for repo
      file: 
        dest: /opt/spring3hibernate
        state: directory

    - name: Cloning repo https://github.com/opstree/spring3hibernate
      git:
        clone: true
        repo: https://github.com/opstree/spring3hibernate.git
        dest: /opt/spring3hibernate

    - name: Generating war file
      command:
        cmd: "mvn clean install"
        chdir: /opt/spring3hibernate

    - name: Add roles to tomcat-users.xml
      lineinfile:
        path: /etc/tomcat10/tomcat-users.xml
        line: "{{ item }}"
        insertbefore: </tomcat-users>
      with_items:
        - '<role rolename="admin-gui"/>'
        - '<role rolename="manager-gui"/>'
        - '<user username="Vikas" password="1234" roles="admin-gui,manager-gui"/>'
      notify: Restart tomcat10

    - name: Copying war file to tomcat webapp directory
      copy:
        src: /opt/spring3hibernate/target/Spring3HibernateApp.war
        dest: /var/lib/tomcat10/webapps
        remote_src: yes
      notify: Restart tomcat10

  handlers:
    - name: Restart tomcat10
      service:
        name: tomcat10
        state: restarted

     
